### ISSUE TITLE
Why  there is failure in registration/login?

### ISSUE THREAD

**Issue by codingpulses** [dejwid/airbnb-clone#3]
please look into the issue and resolve.

**Comment by philip06lee** [comment]
Faced the same problem too. Can't figure out why...

**Comment by codingpulses** [comment]
I cracked it

**Comment by philip06lee** [comment]
can share ? Many thanks!

**Comment by philip06lee** [comment]
Hi Raj,

Can share how you cracked it?

Thanks
Phil

**Comment by codingpulses** [comment]
Sure!

**Comment by codingpulses** [comment]
Please mail me on same Gmail.

**Comment by WhiskeyMaDawg** [comment]
mind sharing the code here? thanks!
